spring:
  mail:
    password: ${EMAIL_PASSWORD}
    username: ${EMAIL}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    mongodb:
      uri: ${MONGO_DB}