spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:events_db;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect