spring:
  datasource:
    url: jdbc:mysql://localhost:3306/events_db?UseSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
